version: '3'

services:
    # crawler:
    #     image: comic-helper:v1.0 
    #     build: .
    #     ports:
    #         - 5000:5000
    #     environment:
    #         - REDIS_HOST=redis
    #         - MYSQL_HOST=mysql
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=testdb
        volumes:
            - /tmp/datadir:/var/lib/mysql
    redis:
        image: redis
        ports:
            - 6379:6379
